### ISSUE TITLE
Font problems in my debian installation

### ISSUE THREAD

**Issue by PaulEJKing** [mbert/elvis#10]
I am accustomed to installing elvis, and while some bugs are fixed (meaning I don't have to go in there and change the code), there is one that has me stumped on your repo.

For one thing, I don't have &lt;X11/Intrinsic.h&gt; in my libraries (or it is hidden somewhere). I had to comment out the reference. It still compiled with GUI. Bit that's not the biggest problem.

I run Ubuntu Studio on my machine, and when I finally run elvis, I get an error
<pre>                        can't load font *-courier-medium-r-*-18-*</pre>
and Elvis does not run. If I run using -G termcap, then the default text in xterm appears black on black. Writing bash code shows syntax highlighting when I tried it, however. I just tried running with -G termcap in a console (not under X), and the default colors where bright yellow on black.a Minor problem. However, I remember Elvis behaving a little funny when one selects "bright" colors, especially if it's default.

Your code has similar strings as <tt>*-courier-medium-r-*-18-*</tt> for bold and oblique, IIRC.

I don't have any fonts on my system that fits that pattern (I checked under xlsfonts and xfontsel). I do, however, have 
<pre>                       *-courier-medium-r-normal-*-17-*</pre>
With absolutely no choice for another font size in that pattern. I can replace the "17" with a "0" to get the default size (which is 17 anyway). Also, note that in the closest match, there was still another "*" before the font size.

If I run the code without installation I get a tiny monospaced font and no toolbar.

**Comment by PaulEJKing** [comment]
I played with it some more this evening, and the command

<pre>$ elvis -courier 17</pre>

generated the same error, but strangely

<pre>$ elvis -courier 0</pre>

gave me a window with proper sized fonts and toolbar. Also, syntax highlighting worked fine, and no command-line error.

**Comment by mbert** [comment]
This is mos likely caused by a font setting in elvis.ini referring to a font that you don't have installed. You should take a look at that file (it's in ELVISDIR, e.g. /usr/local/share/elvis) and play with the settings.

**Comment by mbert** [comment]
I recently noticed a similar problem when running Elvis on a CentOS 6 machine. I could fix it by installing additional fonts:  
xorg-x11-fonts-75dpi.noarch 0:7.2-9.1.el6                 
xorg-x11-fonts-ISO8859-1-75dpi.noarch 0:7.2-9.1.el6
