### ISSUE TITLE
anchor parsing/coloring is hiding a bug

### ISSUE THREAD

**Issue by fbrau** [mbert/elvis#16]
In syntax mode:
after typing an numbered anchor (defined in elvis.syn with a number position, not ^)
the cursor warps to the line below. With the next typed key the cursor restores to the correct line.

To reproduce:
Add a syntax to the default elvis.syn
`language x
extension .x
anchor 1 hola
`

In either termcap or X11:
- `TYPE ANYTHING INTO BUFFER<esc>OholaDid you saw the warp?`
- Now do the same but in an empty-buffer/last-line and I get a segfault

**Comment by ib** [comment]
I can confirm that typing the word _hola_ into the last line of a buffer (or the first line of an empty buffer) will cause a segmentation fault.

**Comment by fbrau** [comment]
i'm not well versed in C but anyways...

I've found the suspicious line:
https://github.com/mbert/elvis/blob/master/dmsyntax.c#L1232

specifically the `prev = *cp` in the forloop accumulator section

**Comment by mbert** [comment]
Should be fixed by latest patch from Ingo Brückl.
