### ISSUE TITLE
After successful build, error upon Elvis instantiation

### ISSUE THREAD

**Issue by Metztli** [mbert/elvis#24]
Niltze [Hi]!

I get this error:

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  144
  Current serial number in output stream:  439

upon Elvis instantiation -- *after* an apparently successful configure (see below, please)
make, make install.

On Debian Sid (Unstable):
./configure --prefix=/usr/local --x-libraries=/usr/lib/x86_64-linux-gnu --verbose
(output)
No system type was specified, so I'm running uname(1) to guess it...
   Apparently this is 'linux'
   I know 'linux' -- This should be easy!
Looking for some compiler files...
   Internet headers found
   Skipping GNOME due to a temporary configuration bug.  (For more information,
      see the comment at the top of the 'configure' script)
   X11 headers found
   X11 libraries found
   GCC found
Assuming --with-x because X11 headers were found
   Enabling the use of background images since -lXpm and &lt;X11/xpm.h&gt; were found
   Xft found -- elvis will use it
Assuming HTTP should be supported because Internet headers were found
Assuming FTP should be supported because Internet headers were found
This system has no &lt;sys/ptem.h&gt; file so I assume elvis doesn't need it
This system has a &lt;termcap.h&gt; file so I assume elvis needs it
This system has a &lt;sys/wait.h&gt; file so I assume elvis needs it
This system has a &lt;sys/select.h&gt; file so I assume elvis needs it
This system has a &lt;sys/ioctl.h&gt; file so I assume elvis needs it
This system has a &lt;netinet/in.h&gt; file so I assume elvis needs it
This system has a &lt;sys/socket.h&gt; file so I assume elvis needs it
This system has a &lt;X11/Xos.h&gt; file so I assume elvis needs it
Does this system support setpgid()?
   Assuming yes, because it is declared in &lt;unistd.h&gt;
Does this system support freopen()?
   Assuming yes, because it is declared in &lt;stdio.h&gt;
Does this system support XrmCombineFileDatabase()?
   Assuming yes, because it is declared in &lt;X11/Xresource.h&gt;
Does this system support inet_aton()?
   Assuming yes, because it is declared in &lt;arpa/inet.h&gt;
Does this system require -lresolv to use inet_aton()?
   Assuming yes, because I found libresolv
Does this system support memmove()?
   Assuming yes, because it is declared in &lt;string.h&gt; or <strings.h>
Choosing a type of ioctl() calls, since no --ioctl=... argument was given
   Assuming --ioctl=termios because &lt;termios.h&gt; exists
For Linux, we're using curses because there is no termcap library
For Linux, elvis never needs &lt;sys/select.h&gt; so I'm ignoring it on your system
Assuming lpout="!lpr" because /usr/bin/lp doesn't exist
Assuming GCC should be used because it exists and the linux-specific
   tweaks didn't indicate that the standard CC is better.
Options:  --prefix=/usr/local --x-libraries=/usr/lib/x86_64-linux-gnu$ --with-x --ioctl=termios --libs='-lcurses'
System:   linux
Compiler: gcc -O2
Bin dir:  /usr/local/bin
Data dir: /usr/local/share/elvis/
Doc dir:  /usr/local/share/elvis/doc/
Man dir:  /usr/local/share/man/elvis/man

Thank you in advance for any insight you can provide.

Best Professional Regards.

**Comment by mbert** [comment]
Please try 57b0757. I was not able to reproduce your problem, but the above patch should fix it.

**Comment by Metztli** [comment]
Indeed, it is fixed. thank you.
Now Elvis lives in Debian Sid with Enlightenment https://www.enlightenment.org/ ;-)

Best Professional Regards.
