### ISSUE TITLE
Gnome & Windows

### ISSUE THREAD

**Issue by malxau** [mbert/elvis#35]
Checkout out this git repo on Windows fails because "IDL:Elvis:ElvisPrivate:1.0.gnorba" is not a valid Windows file name.  Colons are used to indicate alternate streams, and NTFS only supports one level of stream, so "IDL:Elvis" is meaningful, but not beyond that.

In order to checkout this code:
```
git clone https://github.com/mbert/elvis elvis
(fails checking out working copy)
cd elvis
git sparse-checkout init
git sparse-checkout set /* !/guignome/*
git config --worktree --add core.protectntfs false
git checkout master
```

I looked a bit at the guignome code, and I'm wondering if it's worth keeping.  It looks like it's Gnome 1 using Glade, which isn't going to be present on any semi-modern system.  It's also not obvious to me (as someone who knows almost nothing about gnome) whether it's possible to rename this file to something more compatible.

**Comment by mbert** [comment]
Thank you, that was overdue. Since I never actively used the Gnome UI I (and hence never compiled Elvis for it) never ran across it being already so outdated.
