### ISSUE TITLE
Blinking cursor 

### ISSUE THREAD

**Issue by linelec** [mbert/elvis#48]
How to stop the cursor from blinking? I only have this issue with recent distributions (Slackware & Debian). Perhaps it came from latest version of libncurses ?

**Comment by mbert** [comment]
No idea. It's definitely nothing elvis does by itself. Maybe your idea is correct, but nothing I can do here.

**Comment by ib** [comment]
@linelec

For the termcap interface, it should depend on the terminal setting.
