### ISSUE TITLE
Add cyrrilic alphabet support

### ISSUE THREAD

**Issue by AnatoliyL2** [mbert/elvis#50]
I typed 'Элвис' in my file, there were spaces between Э, л, в and и, с was replaced by ? and .

**Comment by AnatoliyL2** [comment]
I think it is very important

**Comment by mbert** [comment]
Nothing we can do here. Elvis does not support unicode, and adding this would be a significant undertaking. 
Since Steve - the original author - no longer maintains the code actively, this isn't likely to be change unless someone else takes on the job.

**Comment by AnatoliyL2** [comment]
> Nothing we can do here. Elvis does not support unicode, and adding this would be a significant undertaking. Since Steve - the original author - no longer maintains the code actively, this isn't likely to be change unless someone else takes on the job.

Ok, ax(my fork of elvis) will have unicode support.

**Comment by AnatoliyL2** [comment]
But when working with latin text, elvis is best text editor(emacs is also good, but it is BLOAT)

**Comment by mbert** [comment]
> > Nothing we can do here. Elvis does not support unicode, and adding this would be a significant undertaking. Since Steve - the original author - no longer maintains the code actively, this isn't likely to be change unless someone else takes on the job.
> 
> Ok, ax(my fork of elvis) will have unicode support.

That would be lovely to see. Let me know when you have something usable. 


> But when working with latin text, elvis is best text editor(emacs is also good, but it is BLOAT)

Sure, that's why I still use it a lot.
